// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/pb/c3.proto

package c3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Jsonrpc              string   `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Params               []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d598b2c1d131a, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Response struct {
	Jsonrpc              string   `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               *any.Any `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d598b2c1d131a, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type PingResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d598b2c1d131a, []int{2}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LatestBlockResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestBlockResponse) Reset()         { *m = LatestBlockResponse{} }
func (m *LatestBlockResponse) String() string { return proto.CompactTextString(m) }
func (*LatestBlockResponse) ProtoMessage()    {}
func (*LatestBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d598b2c1d131a, []int{3}
}
func (m *LatestBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestBlockResponse.Unmarshal(m, b)
}
func (m *LatestBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestBlockResponse.Marshal(b, m, deterministic)
}
func (dst *LatestBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestBlockResponse.Merge(dst, src)
}
func (m *LatestBlockResponse) XXX_Size() int {
	return xxx_messageInfo_LatestBlockResponse.Size(m)
}
func (m *LatestBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestBlockResponse proto.InternalMessageInfo

func (m *LatestBlockResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "c3.Request")
	proto.RegisterType((*Response)(nil), "c3.Response")
	proto.RegisterType((*PingResponse)(nil), "c3.PingResponse")
	proto.RegisterType((*LatestBlockResponse)(nil), "c3.LatestBlockResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// C3Client is the client API for C3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type C3Client interface {
	Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type c3Client struct {
	cc *grpc.ClientConn
}

func NewC3Client(cc *grpc.ClientConn) C3Client {
	return &c3Client{cc}
}

func (c *c3Client) Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/c3.C3/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C3Server is the server API for C3 service.
type C3Server interface {
	Send(context.Context, *Request) (*Response, error)
}

func RegisterC3Server(s *grpc.Server, srv C3Server) {
	s.RegisterService(&_C3_serviceDesc, srv)
}

func _C3_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C3Server).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/c3.C3/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C3Server).Send(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _C3_serviceDesc = grpc.ServiceDesc{
	ServiceName: "c3.C3",
	HandlerType: (*C3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _C3_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/pb/c3.proto",
}

func init() { proto.RegisterFile("rpc/pb/c3.proto", fileDescriptor_b40d598b2c1d131a) }

var fileDescriptor_b40d598b2c1d131a = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4f, 0xc3, 0x20,
	0x18, 0x86, 0x5d, 0xd7, 0x74, 0xfa, 0x6d, 0xd1, 0x04, 0x8d, 0xc1, 0x9d, 0x1a, 0xbc, 0x6c, 0x89,
	0xa1, 0xc9, 0xf8, 0x05, 0xea, 0xd5, 0x83, 0xc1, 0x5f, 0x40, 0x01, 0x6b, 0xb5, 0x03, 0x04, 0x7a,
	0xd8, 0xbf, 0x37, 0x83, 0xce, 0xa3, 0x89, 0x37, 0x9e, 0x97, 0x97, 0x3c, 0x7c, 0x1f, 0x5c, 0x79,
	0x27, 0x1b, 0xd7, 0x36, 0x92, 0x51, 0xe7, 0x6d, 0xb4, 0xa8, 0x90, 0x6c, 0x7d, 0xd7, 0x59, 0xdb,
	0x0d, 0xba, 0x49, 0x49, 0x3b, 0xbe, 0x37, 0xc2, 0x1c, 0xf2, 0x35, 0x91, 0xb0, 0xe0, 0xfa, 0x7b,
	0xd4, 0x21, 0x22, 0x0c, 0x8b, 0xcf, 0x60, 0x8d, 0x77, 0x12, 0xcf, 0xea, 0xd9, 0xe6, 0x82, 0x9f,
	0x10, 0x5d, 0x42, 0xd1, 0x2b, 0x5c, 0xd4, 0xb3, 0x4d, 0xc9, 0x8b, 0x5e, 0xa1, 0x5b, 0xa8, 0xf6,
	0x3a, 0x7e, 0x58, 0x85, 0xe7, 0xa9, 0x38, 0xd1, 0x31, 0x77, 0xc2, 0x8b, 0x7d, 0xc0, 0x65, 0x3d,
	0x3f, 0xe6, 0x99, 0x48, 0x0b, 0xe7, 0x5c, 0x07, 0x67, 0x4d, 0xd0, 0xff, 0xb0, 0x3c, 0x40, 0xe5,
	0x75, 0x18, 0x87, 0x98, 0x2c, 0xcb, 0xdd, 0x0d, 0xcd, 0x63, 0xd0, 0xd3, 0x18, 0xf4, 0xd1, 0x1c,
	0xf8, 0xd4, 0x21, 0x04, 0x56, 0xaf, 0xbd, 0xe9, 0x7e, 0x3d, 0x08, 0x4a, 0x25, 0xa2, 0x98, 0x24,
	0xe9, 0x4c, 0xb6, 0x70, 0xfd, 0x22, 0xa2, 0x0e, 0xf1, 0x69, 0xb0, 0xf2, 0xeb, 0xaf, 0xea, 0x6e,
	0x0b, 0xc5, 0x33, 0x43, 0xf7, 0x50, 0xbe, 0x69, 0xa3, 0xd0, 0x92, 0x4a, 0x46, 0xa7, 0x3d, 0xad,
	0x57, 0x19, 0xf2, 0x63, 0x72, 0xd6, 0x56, 0xe9, 0x3f, 0xec, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17,
	0x21, 0x67, 0x91, 0x7b, 0x01, 0x00, 0x00,
}
